# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 05:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p', '0002_auto_20160304_1525'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Areas',
            new_name='Area',
        ),
    ]
