# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p', '0004_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribed',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
