# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-16 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p', '0005_auto_20160313_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpark',
            name='parkee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p.Parkee'),
        ),
    ]
