# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-25 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p', '0006_auto_20160316_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('city', models.CharField(max_length=40)),
                ('role', models.CharField(choices=[('user', 'user'), ('parkee', 'parkee'), ('parker', 'parker'), ('both', 'both')], max_length=10)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Subscribed',
        ),
    ]
