# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 03:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p', '0007_auto_20160325_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landed',
            old_name='city',
            new_name='suburb',
        ),
    ]
