# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p', '0008_auto_20160326_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='landed',
            name='name',
            field=models.CharField(default='bruce wayne', max_length=40),
            preserve_default=False,
        ),
    ]
