# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('p', '0009_landed_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='landed',
            name='when',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
